export const GET_STATIONS_PENDING = 'GET_STATIONS_PENDING'
export const GET_STATIONS_FULFILLED = 'GET_STATIONS_FULFILLED'
export const GET_STATIONS_REJECTED = 'GET_STATIONS_REJECTED'

export const GET_LINES_PENDING = 'GET_LINES_PENDING'
export const GET_LINES_FULFILLED = 'GET_LINES_FULFILLED'
export const GET_LINES_REJECTED = 'GET_LINES_REJECTED'

export const GET_FARES_PENDING = 'GET_FARES_PENDING'
export const GET_FARES_FULFILLED = 'GET_FARES_FULFILLED'
export const GET_FARES_REJECTED = 'GET_FARES_REJECTED'

export const GET_ZONES_PENDING = 'GET_ZONES_PENDING'
export const GET_ZONES_FULFILLED = 'GET_ZONES_FULFILLED'
export const GET_ZONES_REJECTED = 'GET_ZONES_REJECTED'
