export { default as black_chat } from './black_chat.png'
export { default as black_close } from './black_close.png'
export { default as black_create } from './black_create.png'
export { default as black_feed } from './black_feed.png'
export { default as black_left } from './black_left.png'
export { default as black_search } from './black_search.png'
export { default as black_send } from './black_send.png'
export { default as black_settings } from './black_settings.png'
export { default as black_thumbs_up } from './black_thumbs_up.png'

export { default as gray_clear } from './gray_clear.png'
export { default as gray_thumbs_up } from './gray_thumbs_up.png'

export { default as pink_chat } from './pink_chat.png'
export { default as pink_create } from './pink_create.png'
export { default as pink_feed } from './pink_feed.png'
export { default as pink_not_found } from './pink_not_found.png'
export { default as pink_search } from './pink_search.png'
export { default as pink_settings } from './pink_settings.png'
export { default as pink_thumbs_up } from './pink_thumbs_up.png'
